# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ip.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


##from typing_extensions import Self
from PyQt5 import QtCore, QtGui, QtWidgets
from tkinter import filedialog
from number_of_roots import Ui_Form

class Ui_Browse(object):
    filePath = ""  
    def nextAction(self, data):
        
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Form()
        self.ui.setupUi(self.window, data)
        self.window.show()

    def openFileAction(self, data):
        filename = filedialog.askopenfilename(initialdir = "/",
                                          title = "Select a File",
                                          filetypes = (("Text files",
                                                        "*.txt*"),
                                                       ("all files",
                                                        "*.*")))
        self.address.setText(filename)
        Ui_Browse.filePath = filename 
        data.equation = open(filename, "r").read()
        

        self.Browse = Browse
    
    def setupUi(self, Browse, data):
        self.Browse = Browse
        Browse.setObjectName("Browse")
        Browse.resize(500, 253)
        Browse.setMaximumSize(QtCore.QSize(500, 253))
        self.address = QtWidgets.QLineEdit(Browse)
        self.address.setGeometry(QtCore.QRect(20, 100, 251, 41))
        self.address.setObjectName("address")

        self.browser = QtWidgets.QPushButton(Browse)
        self.browser.setGeometry(QtCore.QRect(320, 110, 111, 28))
        self.browser.setObjectName("browser")
        self.browser.clicked.connect(lambda: self.openFileAction(data))
        
        self.fileAdd = QtWidgets.QLabel(Browse)
        self.fileAdd.setGeometry(QtCore.QRect(20, 60, 121, 21))
        self.fileAdd.setObjectName("fileAdd")
        
        self.next = QtWidgets.QPushButton(Browse)
        self.next.setGeometry(QtCore.QRect(380, 200, 93, 28))
        self.next.setObjectName("next")
        self.next.clicked.connect(lambda: self.nextAction(data))

        self.retranslateUi(Browse)
        QtCore.QMetaObject.connectSlotsByName(Browse)

    def retranslateUi(self, Browse):
        _translate = QtCore.QCoreApplication.translate
        Browse.setWindowTitle(_translate("Browse", "Form"))
        self.browser.setText(_translate("Browse", "Browser"))
        self.fileAdd.setText(_translate("Browse", "FILE ADDRESS"))
        self.next.setText(_translate("Browse", "NEXT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Browse = QtWidgets.QWidget()
    ui = Ui_Browse()
    ui.setupUi(Browse)
    Browse.show()
    sys.exit(app.exec_())
