# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equation.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EqForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.equations = QtWidgets.QTextEdit(Form)
        self.equations.setGeometry(QtCore.QRect(50, 30, 291, 87))
        self.equations.setObjectName("equations")
        self.solve = QtWidgets.QPushButton(Form)
        self.solve.setGeometry(QtCore.QRect(250, 200, 93, 28))
        self.solve.setObjectName("solve")
        self.algorithms = QtWidgets.QComboBox(Form)
        self.algorithms.setGeometry(QtCore.QRect(30, 150, 211, 22))
        self.algorithms.setObjectName("algorithms")
        self.algorithms.addItem("")
        self.algorithms.addItem("")
        self.algorithms.addItem("")
        self.algorithms.addItem("")
        self.algorithms.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.solve.setText(_translate("Form", "Solve"))
        self.algorithms.setItemText(0, _translate("Form", "Bisection"))
        self.algorithms.setItemText(1, _translate("Form", "False-Position"))
        self.algorithms.setItemText(2, _translate("Form", "Fixed Point"))
        self.algorithms.setItemText(3, _translate("Form", "Newton Raphson"))
        self.algorithms.setItemText(4, _translate("Form", "Secant"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_EqForm()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
