# # -*- coding: utf-8 -*-

# # Form implementation generated from reading ui file 'ip.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.6
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.


# from tkinter import Label, filedialog
# from tkinter import *
# from PyQt5 import QtCore, QtGui, QtWidgets
# from equations import Ui_EqForm


# class Ui_Form(object):
    
#     def setupUi(self, Form):
#         Form.setObjectName("Form")
#         Form.resize(500, 253)
#         Form.setMaximumSize(QtCore.QSize(500, 253))
    
#         self.address = QtWidgets.QLineEdit(Form)
#         self.address.setGeometry(QtCore.QRect(30, 60, 251, 41))
#         self.address.setObjectName("address")
    
#         def browseAction():
#             filename = filedialog.askopenfilename(initialdir = "/",
#                                           title = "Select a File",
#                                           filetypes = (("Text files",
#                                                         "*.txt*"),
#                                                        ("all files",
#                                                         "*.*")))
#             self.address.setText(filename)

#         self.browser = QtWidgets.QPushButton(Form)
#         self.browser.setGeometry(QtCore.QRect(310, 70, 111, 28))
#         self.browser.setObjectName("browser")
#         self.browser.clicked.connect(browseAction)
        
#         def enterEqu():
#             self.window = QtWidgets.QMainWindow()
#             self.ui = Ui_EqForm()
#             self.ui.setupUi(self.window)
#             self.window.show()

#         self.eqn = QtWidgets.QPushButton(Form)
#         self.eqn.setGeometry(QtCore.QRect(60, 160, 81, 20))
#         self.eqn.setObjectName("entereq")
#         self.eqn.clicked.connect(enterEqu)
        
#         #open file in read mode and get equations
#        # def openfileAction():
#         #    file = open(,"r")
            

#         self.opfile = QtWidgets.QPushButton(Form)
#         self.opfile.setGeometry(QtCore.QRect(60, 130, 81, 20))
#         self.opfile.setObjectName("openfile")
#         #self.opfile.clicked.connect(openfileAction)

#         self.retranslateUi(Form)
#         QtCore.QMetaObject.connectSlotsByName(Form)

#     def retranslateUi(self, Form):
#         _translate = QtCore.QCoreApplication.translate
#         Form.setWindowTitle(_translate("Form", "Form"))
#         self.browser.setText(_translate("Form", "Browser"))
#         self.eqn.setText(_translate("Form", "entereq"))
#         self.opfile.setText(_translate("Form", "openfile"))

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
