# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'output.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_output(object):
    def setupUi(self, output):
        output.setObjectName("output")
        output.resize(667, 706)
        output.setAutoFillBackground(False)
        self.iteration_label = QtWidgets.QLabel(output)
        self.iteration_label.setGeometry(QtCore.QRect(20, 10, 141, 31))
        self.iteration_label.setObjectName("iteration_label")
        self.iteration_value = QtWidgets.QLabel(output)
        self.iteration_value.setGeometry(QtCore.QRect(270, 20, 55, 16))
        self.iteration_value.setObjectName("iteration_value")
        self.time_label = QtWidgets.QLabel(output)
        self.time_label.setGeometry(QtCore.QRect(20, 50, 141, 21))
        self.time_label.setObjectName("time_label")
        self.time_value = QtWidgets.QLabel(output)
        self.time_value.setGeometry(QtCore.QRect(270, 50, 55, 16))
        self.time_value.setObjectName("time_value")
        self.root_label = QtWidgets.QLabel(output)
        self.root_label.setGeometry(QtCore.QRect(20, 90, 141, 21))
        self.root_label.setObjectName("root_label")
        self.root_value = QtWidgets.QLabel(output)
        self.root_value.setGeometry(QtCore.QRect(270, 90, 55, 16))
        self.root_value.setObjectName("root_value")
        self.precision_label = QtWidgets.QLabel(output)
        self.precision_label.setGeometry(QtCore.QRect(20, 120, 141, 21))
        self.precision_label.setObjectName("precision_label")
        self.precision_value = QtWidgets.QLabel(output)
        self.precision_value.setGeometry(QtCore.QRect(270, 120, 55, 16))
        self.precision_value.setObjectName("precision_value")
        self.tabel_iteration = QtWidgets.QTableWidget(output)
        self.tabel_iteration.setGeometry(QtCore.QRect(20, 170, 631, 371))
        self.tabel_iteration.setObjectName("tabel_iteration")
        self.tabel_iteration.setColumnCount(0)
        self.tabel_iteration.setRowCount(0)

        self.retranslateUi(output)
        QtCore.QMetaObject.connectSlotsByName(output)

    def retranslateUi(self, output):
        _translate = QtCore.QCoreApplication.translate
        output.setWindowTitle(_translate("output", "Output"))
        self.iteration_label.setText(_translate("output", "Number Of Iteration"))
        self.iteration_value.setText(_translate("output", "50"))
        self.time_label.setText(_translate("output", "Execution Time (sec.)"))
        self.time_value.setText(_translate("output", "3000"))
        self.root_label.setText(_translate("output", "Approximate Root"))
        self.root_value.setText(_translate("output", "5"))
        self.precision_label.setText(_translate("output", "Precision"))
        self.precision_value.setText(_translate("output", "0.00005"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    output = QtWidgets.QDialog()
    ui = Ui_output()
    ui.setupUi(output)
    output.show()
    sys.exit(app.exec_())
